FROM continuumio/miniconda:4.7.12

RUN apt-get update
RUN apt-get install -y git wget unzip libgl1-mesa-glx

RUN git config --global user.name hyunseoki
RUN git config --global user.email hyunseoki@kaist.ac.kr


CMD ["/bin/bash"]